"""changing claim default

Revision ID: 95e8e2ee504e
Revises: 76b7acd277b0
Create Date: 2024-02-22 16:08:08.975216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e8e2ee504e'
down_revision = '76b7acd277b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('select', sa.Boolean(), server_default='false', nullable=False))
        batch_op.drop_column('selected')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.drop_column('select')

    # ### end Alembic commands ###
