"""ratings columns in User is now an array

Revision ID: e9fc1b5ff2d4
Revises: df5ca284ad04
Create Date: 2024-02-28 12:12:51.251506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9fc1b5ff2d4'
down_revision = 'df5ca284ad04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', postgresql.ARRAY(sa.Integer()), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('ratings')

    # ### end Alembic commands ###
